### ISSUE TITLE
python-check-mock-methods complains about existing methods in docstring

### ISSUE THREAD

**Issue by torfsen** [pre-commit/pygrep-hooks#21]
I have a function with a docstring that looks like this:

```
def foo(m: Mock, *args, **kwargs):
    """
    ...

    This function is similar to :meth:`Mock.assert_called_once_with`,
    but ...

    ....
    """
```
`python-check-mock-methods` complains about this:
```
tests/conftest.py:86:    This function is similar to :meth:`Mock.assert_called_once_with`,
```
I don't understand that, because [that method exists](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_called_once_with).

**Comment by torfsen** [comment]
I've also run into a similar case with [`Mock.assert_any_call`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_any_call).

**Comment by asottile** [comment]
it complains because it's a very simple regex, it probably won't be able to accommodate every case

the reason it detects it is it errors on anything that is missing parentheses (as is common for developers coming from, for example, ruby where parens are optional)

one way you could make this work is to adjust the regex to explicitly allow `"Mock"` as the target name (probably with a [negative lookbehind](https://docs.python.org/3/library/re.html#index-23))

would you like to take a stab at it? it should be pretty easy to add a test [here](https://github.com/pre-commit/pygrep-hooks/blob/a61352d479060b074f1640b9124ef122a969bbb5/tests/hooks_test.py#L78-L89) and then adjust the regex [here](https://github.com/pre-commit/pygrep-hooks/blob/a61352d479060b074f1640b9124ef122a969bbb5/.pre-commit-hooks.yaml#L9-L28)

**Comment by asottile** [comment]
@torfsen ping! would you like to take a stab at this one?

**Comment by torfsen** [comment]
@asottile I currently don't have time for it but may come back to it later.

**Comment by mik-laj** [comment]
In my opinion, it will be easiest to add a new rule for pylint. It is very difficult to know the context using only the regular expression. It would be very useful to know all the grammar and have an AST tree.

**Comment by asottile** [comment]
but... it already works?
